spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notificationDB
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: com.clone.backend.linkedin.*

server:
  port: 9040
  servlet:
    context-path: /notifications
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

